### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by vLaznikova** [ethvis/qd-track#1]
Hi,
Is there a option to download pretrained model?
Thanks.

**Comment by OceanPang** [comment]
@vLaznikova Hi, we are preparing the pre-trained weights and will release the models here ASAP.

**Comment by vLaznikova** [comment]
> @vLaznikova Hi, we are preparing the pre-trained weights and will release the models here ASAP.

Thanks!

**Comment by bhautik-pithadiya** [comment]
are the pre-trained weights available now??
