### ISSUE TITLE
Data folder structure

### ISSUE THREAD

**Issue by vLaznikova** [ethvis/qd-track#2]
Hi,
My initial plan is to test the pretrained models you've provided.

I'm having a trouble with running bdddet2coco.py
The error I get:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mfm/repos/QD/data1/det_v2_train_release.json'

I followed the data sctructure as described in :
https://github.com/ethvis/qd-track/blob/master/docs/GET_STARTED.md#prepare-datasets

Can you please add the instructions on the dataset preparation?

Thanks!

**Comment by OceanPang** [comment]
Hi @vLaznikova , as in the instructions, you need to download the official annotations first, then 
`python bdddet2coco.py -i ${path of offical files} -o ${path of out files}`, then put the outputted annotations files following the structures.
